<?php
// Start the session
session_start();

// Include necessary libraries for payment processing (e.g., Stripe or PayPal)
// require 'vendor/autoload.php'; // Uncomment if using Composer for libraries

// Database connection (if needed)
// $conn = new mysqli('host', 'username', 'password', 'database');

// Check for form submission
if ($_SERVER["REQUEST_METHOD"] == "POST") {
    // Get form data
    $name = htmlspecialchars(trim($_POST['name']));
    $email = htmlspecialchars(trim($_POST['email']));
    $amount = htmlspecialchars(trim($_POST['amount']));
    $payment_method = htmlspecialchars(trim($_POST['payment_method']));

    // Validate form data
    if (empty($name) || empty($email) || empty($amount) || empty($payment_method)) {
        die("Please fill in all fields.");
    }

    // Payment processing (example with Stripe)
    // Uncomment and configure if using Stripe
    /*
    \Stripe\Stripe::setApiKey('your_stripe_secret_key');

    try {
        $charge = \Stripe\Charge::create([
            'amount' => $amount * 100, // Amount in cents
            'currency' => 'usd',
            'description' => 'Donation from ' . $name,
            'source' => $_POST['stripeToken'], // Token generated by Stripe.js
        ]);
    } catch (\Stripe\Exception\CardException $e) {
        die("Payment failed: " . $e->getMessage());
    }
    */

    // Send confirmation email to donor
    $to = $email;
    $subject = "Thank You for Your Donation!";
    $message = "Dear $name,\n\nThank you for your generous donation of $$amount.\n\nYour support helps us continue our mission.\n\nBest regards,\nWawa Seed Africa Foundation";
    $headers = "From: no-reply@yourdomain.com";

    if (mail($to, $subject, $message, $headers)) {
        echo "Thank you for your donation! A confirmation email has been sent to $email.";
    } else {
        echo "Thank you for your donation! However, we couldn't send a confirmation email.";
    }

    // Optionally, save donation details to the database
    /*
    $stmt = $conn->prepare("INSERT INTO donations (name, email, amount, payment_method) VALUES (?, ?, ?, ?)");
    $stmt->bind_param("ssis", $name, $email, $amount, $payment_method);
    $stmt->execute();
    $stmt->close();
    */

    // Close the database connection
    // $conn->close();
} else {
    echo "Invalid request.";
}